var hello = "Hello!";
console.log(hello);
var combine1 = "My name is";
console.log(combine1);
var combine2 = "Akshith Chalamalasetty";
console.log(combine2);
var fullcombine = combine1.concat(combine2);
console.log(fullcombine);
var transition = "Now let's do some mathematical operations!";
console.log(transition);
var firstvar = 23481234;
console.log(firstvar);
var times = "×";
console.log(times);
var secondvar = 3927402987;
console.log(secondvar);
var equal = "=";
console.log(equal);
var multiply = firstvar*secondvar;
console.log(multiply);
var dividevar1 = 625;
console.log(dividevar1);
var divide_symbol="÷";
console.log(divide_symbol);
var dividevar2 = 15;
console.log(dividevar2);
var equal1 = "=";
console.log(equal1);
var finaldivide = dividevar1/dividevar2;
console.log(finaldivide);

